// SPDX-License-Identifier: LGPL-3.0-only OR LicenseRef-Taira-Commercial
// Copyright (c) 2025 Taira. All rights reserved.

import Foundation

// MARK: - Lifecycle management

extension WireGuardTunnel {
	/// Starts the periodic tick task for tunnel maintenance.
	///
	/// This method creates and stores a background task that calls the processor's
	/// tick() method at regular intervals. The tick operation performs essential
	/// tunnel maintenance including:
	///
	/// - Sending keepalive packets if configured
	/// - Checking for handshake timeouts
	/// - Expiring old sessions
	/// - Initiating rekeys when needed
	///
	/// The tick interval is set to 100 milliseconds (10 ticks per second), which
	/// provides good responsiveness for keepalives and timeouts without excessive
	/// CPU usage.
	///
	/// The task is automatically cancelled when the tunnel stops or is deallocated.
	internal func startTickTask() {
		// Cancel any existing tick task first
		tickTask?.cancel()

		// Create new tick task
		tickTask = Task { [weak self] in
			// Tick every 100ms (recommended range is 10-100ms)
			while !Task.isCancelled {
				do {
					// Perform tick operation
					if let packet = try await self?.processor.tick() {
						// Packet should be sent to peer endpoint when NetworkExtension integration is complete.
						// For now, we discard keepalive and handshake packets generated by the tick operation.
						_ = packet
					}

					// Sleep until next tick
					try await Task.sleep(nanoseconds: 100_000_000)  // 100ms in nanoseconds
				} catch {
					// If tick fails, transition to error state
					if let self = self {
						await self.transitionState(
							to: .error("Tick failed: \(error.localizedDescription)"))
					}
					break
				}
			}
		}
	}
}
